import os
from unittest.mock import MagicMock, patch

import pytest
from atelier.durability.bigquery_ml_helper import BigQueryMLHelper


@patch("atelier.durability.bigquery_ml_helper._bq_enabled")
def test_setup_remote_model_disabled(mock_enabled):
    """Verify that setup is a no-op when BigQuery is disabled."""
    mock_enabled.return_value = False

    helper = BigQueryMLHelper(project_id="my-project")
    res = helper.setup_remote_model()

    assert res is False


@patch("atelier.durability.bigquery_ml_helper._bq_enabled")
@patch("atelier.durability.bigquery_ml_helper.bigquery")
def test_setup_remote_model_success(mock_bq, mock_enabled):
    """Verify that setup runs the creation queries and returns True on success."""
    mock_enabled.return_value = True

    mock_client = MagicMock()
    mock_bq.Client.return_value = mock_client

    # Mock query job
    mock_job = MagicMock()
    mock_client.query.return_value = mock_job

    helper = BigQueryMLHelper(project_id="my-project")
    res = helper.setup_remote_model()

    assert res is True
    assert mock_client.query.call_count == 1
    assert "CREATE OR REPLACE MODEL" in mock_client.query.call_args[0][0]


@patch("atelier.durability.bigquery_ml_helper._bq_enabled")
@patch("atelier.durability.bigquery_ml_helper.bigquery")
def test_query_telemetry_conversational_success(mock_bq, mock_enabled):
    """Verify that natural language query is translated to SQL and executed."""
    mock_enabled.return_value = True

    mock_client = MagicMock()
    mock_bq.Client.return_value = mock_client

    # Mock ML.GENERATE_TEXT translation result
    mock_translation_job = MagicMock()
    mock_translation_job.result.return_value = [
        {
            "ml_generate_text_result": "```sql\nSELECT * FROM trajectories WHERE tenant_id = 'tenant-y'\n```"
        }
    ]

    # Mock final SQL execution result
    mock_sql_job = MagicMock()
    mock_sql_job.result.return_value = [{"session_id": "sess-1", "converged": True}]

    mock_client.query.side_effect = [mock_translation_job, mock_sql_job]

    helper = BigQueryMLHelper(project_id="my-project")
    results = helper.query_telemetry_conversational("Show all converged runs for tenant-y")

    assert len(results) == 1
    assert results[0]["session_id"] == "sess-1"
    assert mock_client.query.call_count == 2

    # Verify first query was ML.GENERATE_TEXT
    assert "ML.GENERATE_TEXT" in mock_client.query.call_args_list[0][0][0]
    # Verify second query was the translated SQL
    assert "SELECT * FROM trajectories" in mock_client.query.call_args_list[1][0][0]


@patch("atelier.durability.bigquery_ml_helper._bq_enabled")
def test_query_telemetry_conversational_disabled(mock_enabled):
    """Verify that query returns empty list when BigQuery is disabled."""
    mock_enabled.return_value = False

    helper = BigQueryMLHelper(project_id="my-project")
    results = helper.query_telemetry_conversational("Show all runs")

    assert results == []


@patch("atelier.durability.bigquery_ml_helper._bq_enabled")
@patch("atelier.durability.bigquery_ml_helper.bigquery")
def test_query_telemetry_conversational_unsafe_queries(mock_bq, mock_enabled):
    """Verify that unsafe queries generated by the LLM are blocked and not executed."""
    mock_enabled.return_value = True

    mock_client = MagicMock()
    mock_bq.Client.return_value = mock_client

    helper = BigQueryMLHelper(project_id="my-project")

    # Case 1: Non-SELECT query
    mock_translation_job = MagicMock()
    mock_translation_job.result.return_value = [
        {"ml_generate_text_result": "DELETE FROM trajectories WHERE tenant_id = 'tenant-y'"}
    ]
    mock_client.query.return_value = mock_translation_job

    results = helper.query_telemetry_conversational("Delete all data")
    assert results == []
    assert mock_client.query.call_count == 1

    mock_client.reset_mock()

    # Case 2: Query containing forbidden keyword
    mock_translation_job.result.return_value = [
        {"ml_generate_text_result": "SELECT * FROM trajectories; DROP TABLE trajectories;"}
    ]
    results = helper.query_telemetry_conversational("Drop table")
    assert results == []
    assert mock_client.query.call_count == 1
