import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Atelier — Terms of Service',
  description: 'Terms of Service for the Atelier autonomous design agent platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[var(--g-bg)] stitch-grid-bg py-16 px-6 flex justify-center">
      <div className="w-full max-w-3xl g-card p-10 bg-[var(--g-surface)]/80 backdrop-blur-xl shadow-2xl relative">
        <header className="mb-10 border-b border-[var(--g-outline)] pb-6 flex flex-col gap-4">
          <div className="w-12 h-12 rounded-xl bg-black flex items-center justify-center border border-neutral-800 shadow-[0_0_16px_rgba(255,255,255,0.05)]">
            <svg
              className="w-5 h-5"
              viewBox="0 0 1155 1000"
              fill="none"
              role="img"
              aria-label="Atelier Logo"
            >
              <path d="m577.3 0 577.4 1000H0z" fill="#fff" />
            </svg>
          </div>
          <div>
            <h1 className="text-3xl font-medium tracking-tight text-white">
              Atelier Terms of Service
            </h1>
            <p className="text-xs text-[var(--g-text-muted)] font-mono mt-1">
              Effective Date: June 5, 2026
            </p>
          </div>
        </header>

        <div className="space-y-8 text-sm text-[var(--g-text-muted)] leading-relaxed">
          <section>
            <p>
              Welcome to <strong>Atelier</strong>. These Terms of Service (&quot;Terms&quot;) govern
              your access to and use of the Atelier platform, including our website, APIs, and
              autonomous AI agents (collectively, the &quot;Services&quot;). By using our Services,
              you agree to be bound by these Terms. If you do not agree, please do not use the
              Services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">1. Description of Services</h2>
            <p>
              Atelier is an autonomous multi-agent design platform that compiles high-fidelity,
              production-ready, and accessible user interfaces from natural language briefs. The
              Services are powered by AI models running on Google Cloud and Vertex AI. We
              continuously improve and update our Services to provide optimal capabilities.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">2. Eligibility and Account Setup</h2>
            <p>
              To access certain features of Atelier, you must register for an account using Google
              OAuth. By creating an account, you represent and warrant that:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You are at least 18 years of age or the age of majority in your jurisdiction.</li>
              <li>All information you provide is accurate and up-to-date.</li>
              <li>
                You are solely responsible for maintaining the confidentiality of your account
                credentials and for all activities that occur under your account.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">
              3. Intellectual Property Rights &amp; Ownership
            </h2>
            <p>
              <strong>Your Designs and Code:</strong> As between you and Atelier, you retain all
              ownership, copyright, and intellectual property rights in the user interface designs,
              code components, and assets generated by Atelier based on your design briefs, subject
              to your compliance with these Terms. You are free to export, deploy, license, and
              commercialize the generated code for any project.
            </p>
            <p>
              <strong>Platform Ownership:</strong> Atelier retains all rights, title, and interest
              in and to the platform, core agent codebases, algorithms, multi-agent frameworks,
              design-token engines, and any software, tools, or documentation provided by us. You
              may not reverse engineer, decompile, or attempt to extract the source code of the
              Atelier platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">4. Acceptable Use Policy</h2>
            <p>You agree not to use Atelier to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                Generate code, applications, or designs that contain malware, spyware, or other
                harmful software components.
              </li>
              <li>
                Infringe the intellectual property rights, privacy rights, or publicity rights of
                any third party.
              </li>
              <li>
                Build products, systems, or tools that violate applicable local, national, or
                international laws.
              </li>
              <li>
                Interfere with or disrupt the integrity or performance of the Services or Google
                Cloud infrastructure.
              </li>
              <li>
                Violate the Google Cloud Platform and Google Generative AI Additional Terms of
                Service.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">5. Disclaimer of Warranties</h2>
            <p>
              Atelier is provided on an &quot;as is&quot; and &quot;as available&quot; basis,
              without any warranties of any kind. Because the Services rely on advanced generative
              AI technology, we do not guarantee that the generated code is completely free of bugs,
              security vulnerabilities, or accessibility issues. You are solely responsible for
              reviewing, testing, and verifying all generated output prior to production deployment.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Atelier and its contributors shall not be
              liable for any indirect, incidental, special, consequential, or punitive damages, or
              any loss of profits or revenues, whether incurred directly or indirectly, or any loss
              of data, use, goodwill, or other intangible losses, resulting from (a) your use or
              inability to use the Services, or (b) any errors, omissions, or security
              vulnerabilities in any code generated by the AI platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">7. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of any material changes by
              posting the updated Terms on this page. Your continued use of the Services after the
              effective date of any changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-medium text-white">8. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              State of California, without regard to its conflict of law principles.
            </p>
          </section>
        </div>

        <footer className="mt-12 border-t border-[var(--g-outline)] pt-6 flex justify-between items-center text-xs text-[var(--g-text-muted)]">
          <span>&copy; 2026 Atelier. All rights reserved.</span>
          <Link href="/privacy" className="text-[var(--g-info)] hover:underline">
            Privacy Policy
          </Link>
        </footer>
      </div>
    </main>
  );
}
